input_data:
  marathon_data: "../data/raw/Berlin_Marathon_data_1974_2019.csv"
  marathon_winners: "../data/raw/berlin_marathon_winners_1974_2024.csv"

output_data:
  cleaned_data: "../data/clean/cleaned_marathon.csv"
  cleaned_winners: "../data/clean/cleaned_marathon_winners.csv"

